def reverse (text):
    return text [::-1]

def complement (text):
    Complemented_string = ""
    Complemented_dict = {'A': 'T', 'T':'A', 'C':'G','G':'C' }
    for base in text:
        Complemented_string += Complemented_dict.get(base,base)
    return Complemented_string 

def reverse_complement(text):
    return reverse(complement(text))


text = "AATATTAGTCTTAACCAGTATTTCCGATATTACGTAGCAAGGATTGTCTGCTTAGAACGCCTAAATACGCGTTGGACGTTACAGGGCCTCCATATTAAGTTGCGATCCTCGTTTCATTCGTTCTTGTCGTTATACGACGTCCATTTCAGGCCTCTATTTAAGCTCACCTAATTCATATGATAGGAGGGGCCGGATGGACCCGAGGTATTGGAAATAAGTTATGGATGGAGCCATCTTTGGAAAAAGTCAGCACATATGCAATTTTAGCTTGGAAAGATTCAGCTCCAGTCAAGGCCTCCTAGAACCTGTCCCGTGATCCACATAGGAGACTGATGGGCCACTGTATTTCAACGCTGAGTCGCATCAAGCAGCGTTTTACCTATGGTTGAGGTGAACGGAATTATTGTTCGACCCGGCTCAACCAAAAACGGGCGTACCCCGTGGGCCTGCTCTCTGGTGGCAGGCTTTCCCGCCGTTAACTATATGGTGGTAACCATTCCTCTATGGAGAGCCTACGTATCTTCCCAACTTATCGGCGGAGTGTGGAAACCATTCCCATAGCAATATGGGAAAAATCCGAAGGGATCAACATATATGAGCGCGTGTGGGGGTTAGAGCCTCCATTGTTCCCTTACTCTTTGCCAGTTGTGAGGGAGCTGCCGTCAAGTTGAGGATGTCGTGCTGTCACTAGAATAAAGATGATGATCTCTGACTATCCAGAGACCCTCCGAAGCTGCATCGATGTGATTCCAGCCGTGGCAGGTTCACATATGTAGTAAAACTCTAATTGTGGCCGCAAGTACTTTAGCGTCAACCTGCTATGCT"
print (reverse_complement(text))