def count_nt(Text):
    freq = {}
    n = len(Text)

    for i in range(n):
        nucleotide = Text[i]
        freq[nucleotide] = 0

        for j in range(n):
            if Text[j] == nucleotide:
                freq[nucleotide] += 1

    return freq

Text = "GGGAATAGCTACGGACATCTGACATTCATTGTTGAGTCATTACTCGGTGTTGGGGAGGATACGGACAATCCCCCCGGGTTGATGGGACAAAATGTTCGCAATTGATACGCATAATCTAACAAAGTCCCGCGCTTTTGCCGAGGGTTGTCGACATAGTACCCAATCGTTCTCAAGACGTACACCGGGCTAAGTCTTCAAACATACCATCTCAAAGCGTCGGTCCCTTTATACTAAAGTCAGGGACTTGTCCCACGGTACACCTACAGAGGCAAAAAGGTTTTTCTTGGGGCGACCGGGCTTTATGCCACTCAACACAAATTCGCTCGTTAAGGTTGATCTCAACTAGAACCCGTAAGAAAGGATAGAGCTAGTAATGAGCCCAGTACGGTGAGCAAATGAGTTCCCTGAGGGTTGCTCAGTGTGTATGGCTACGGCGCCGCTATTCCCCTGAATTGAGCTTAGCGCCTCGCTCGGACGCCAAGCCATTACGAAGGCCTATGATGGTTTAATATCCGATGGCAGAAATAAGGGAAAGCTATCTGGACCGACTAACTAAATGTTGTTTAATCGAGCGCTACCAAGGGCGTGCGCAGCTGCAACGCGTCCGCAGTAATGACAGAGCAGTAAATACGCGATCTTACGTGCTGCTGAGCCTAAACTAGTGTCCATTTAATTTAATCCCAGTCATTAATAGGCCCCCAGGAATCACTAGGAATAGGGGCAGCCTTTGAACTAAGGCTACCTAAAGAAAAGTTGCGGCAGTCCTTGTACTCGCAATATAAATGGGGCGGCGATCCACTATATTAAGTACGTAGTACTGAGTCGGAAGTGACGCGCCGGCAGACGTCGGTGAGCGCTATGAAGATGGGACGATATGTGGTATGATATAGAGGAATTGAGTAAGTCGGGGTATGAATAGTCGATTTGGGGAAACGGCTCAACGCCAGCCGGCGTT"
print(count_nt (Text))
print(len(Text))