def transcribe(Text):
    n = len(Text)
    transcribed_sequence = ""

    for i in range(n):
        nucleotide = Text[i]
        if nucleotide == "T":
            transcribed_sequence += "U"
        else:
            transcribed_sequence += nucleotide

    return transcribed_sequence

Text = "TATTTAACCTCTGACCTTGGACGCTGGAACAGCCGGACCCAAGAGCACCATAATGTGAACAGTATGTTGGAAGTCGTTTCTAATTATTGGCAGCTTTAGCATCACCAAAAAATTACACGGTCAAGAGAGTTACGCCGCTCGATAATCGCCGAATATTAATCCCCGTCGTTGCTGGAGCGACCTACGTAGCCGTTAGAGTTAAATATACCGTCTGGGTCGCAGGCGCGATTGGCCAAGTCCCAAGTGGTGGAAAAACCATGTGGGGCGTTGCGATTTTCAATCACCTTGTTATGCCTTGAGTGAGACCACGAGCAGCTCGTCCTTAATGCTATCTACTATGCCAAGGGGTCTACGGAGGACTGTCATTCGAGTGAGCTCCGTTCCGTAAGTATGGAAGGTTGACCGTGTGACGGGGGGTCTGGTCGTCTTTGTAAGCGGTCGTCGCGGCAGAGAGTTGGCGGACACTGGTCGGTCTGAACCGCCGTTAGGACCATTTTCACTCATGAAGAGATGCAGAATTCAGGTAACTGGTGGTGCGTTTACAGGTACACAGGGTTCCTTCCACACGGGGCCCAATCTTGCGATGTCATCGAGTTCCGCATCGTTCCACAAGCTTTGCTATATACCCGTGGCTCTAAGATTAGGCTATTAGTTGCTATAACCAATAAAGTGGCCTACGCCTGTTGGATCTCAAAGATACCCATCTTCGTATAATGCCGTCATTGTAATAAGTTGATCCACAAGGTGGTTTCCATGACGGGGGCCCGATTCTAACACCGAGGCCTGTTATCGGAAGAGGAGTTCCCTACAGCCGACGCCTATACGCGTATTAATTCTTAAACCGAGGCGCGAACGATGGAGCTAGATTCATGTAGATTGACTAACAATGTCAACGCGTCGACCAATTGTGCGAATATGCCGAATCTTAAATCATGGTGCACCATTAGAGAGAGAGCCTAGCCGGGATAAAACGGTCATGGTTTATTTCGGTTATCTGAG"
print(transcribe(Text))
