'''
A solution to a ROSALIND bioinformatics problem.

Problem Title: Inferring mRNA from Protein
Rosalind ID: MRNA
Rosalind #: 017
URL: http://rosalind.info/problems/mrna/
'''
def count_rna_strings(protein):
    # Codon table for RNA
    codon_table = {
        'F': 2, 'L': 6, 'I': 3, 'M': 1,
        'V': 4, 'S': 6, 'P': 4, 'T': 4,
        'A': 4, 'Y': 2, 'H': 2, 'Q': 2,
        'N': 2, 'K': 2, 'D': 2, 'E': 2,
        'C': 2, 'W': 1, 'R': 6, 'G': 4
    }
    # Number of stop codons
    stop_codons = 3
    # Modulo value
    modulo = 1000000

    # Initialize the count
    total_count = 1

    # For each amino acid in the protein string, multiply the count
    for aa in protein:
        total_count = (total_count * codon_table[aa]) % modulo

    # Multiply by the number of stop codons
    total_count = (total_count * stop_codons) % modulo

    return total_count

# Example usage:
protein_string = "MNVQNPLWPAEQARIFCFFVMLINRAATVHNAKKEKQFHQHHVRISENDCLHFQMESIDNGAGHLANDFHPRKRFHNDHFRDNPYILTYEKIIVAFAMKSVVKYTMLEWYYPRWDCQYESIPGRMVKGGYKPNNIPDDDWWDMINMELWRGQRDRWSIHAQLPQWRPRDFQPCTSHRDEESWTTVRCKPYMEKKHPKSIYVFVGMEFPSYPNLCHAAVIYAMHDQLVSNGYEANRAGRKTDPFNRKSGNHYLYPLCDEWAGMQYLYRNLYLWIVVEEDLRQKRNLHPSAFCDIIKESNHPKWQGDKPCPKADFHGSAKCHHTDVQTSCPINASNDMHANCDDTPPRIIENQYEVRLNPAHRVWGDWISFAMYYHYGMVMKCTAVHIIAYVENETPWEKACSTKMITICYHTFWDLDTRPLIKYANPSVWLGCRGFTGMTVRVWFPVGMKQNICHQWKVTDCVQCMEWMTVQFDSAKYIQQFLCDIVKSDNFMFEFISTNHFIHAGDWELNYNWQGVEFWACAYVREQWVCFGGCGQEPSLQPWVEGCNASDRLLIFIKLVGFAQWDMPWTADTLKITYTQLFRFERRVRCNDQQTYAFFDIDYPRYRFFLPACPPPSQKVSPIWSGIYDLAPLVLRMHMWMECQNYAGALFGYKCSPNNRNKAICHIAQKMHTEEDAHVPIQVVPRRFWVHDDIMWALCVATNYLVKHVWSVYQDGLKDLAMVVYDDLAMFLFTDLSIHLVGNDHVPRKGHCWEIMNAAVWSLACECGTPPDAVKMYIELVTFRLRWCEWLMQGNHQTAKCKTVNDMQTCEVHFSYEYAAECWHNCGLFWDCLWMGIKPFFRSVRFYWLGIDNVNGWPPQENNVPCRQRWMFVVPEGFLAHTCSENCWDARGEPLRLCQMESTNSSPLDSRIANMGGGMMMLEFMFTMYEHSHAAPMGPRQCPACRGLEKEVGWAVDCNQQIAMLSDKHILVYMMFYELRTWCHNEDLHEWHYTCIQF"
print(count_rna_strings(protein_string))  # Output: 3
